[package]
name = "sonic-os"
version = "0.1.0"
edition = "2021"
authors = ["hao.zhen <i_zhenhao@163.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.23"
